type=item
matchItems=bow
model.bow_standby=pistol
model.bow_pulling_0=pistol_pulling_0
model.bow_pulling_1=pistol_pulling_1
model.bow_pulling_2=pistol_pulling_2
nbt.display.Name=ipattern:\u0413\u043b\u043e\u043a 17
#Глок 17