type=armor
matchItems=chainmail_helmet golden_helmet iron_helmet diamond_helmet netherite_helmet

texture.chainmail_layer_1=diamond_layer_1
texture.gold_layer_1=diamond_layer_1
texture.iron_layer_1=diamond_layer_1
texture.diamond_layer_1=diamond_layer_1
texture.netherite_layer_1=diamond_layer_1

nbt.display.Name=ipattern:*\u041a\u0432\u0430\u0440\u0446\u0435\u0432\u044b\u0439 \u0410\u043a\u0441\u0435\u0441\u0441\u0443\u0430\u0440*
#Кварцевый Аксессуар