type=item
matchItems=iron_leggings chainmail_leggings diamond_leggings golden_leggings netherite_leggings leather_leggings
texture=plaid_pants_icon
nbt.display.Lore.*=ipattern:*\u041a\u043b\u0435\u0442\u0447\u0430\u0442\u044b\u0435 \u0448\u0442\u0430\u043d\u044b \"DinBi\"*
