type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=fist
nbt.display.Name=ipattern:*\u041d\u0435\u0432\u0438\u0434\u0438\u043c\u044b\u0439 \u041a\u0443\u043b\u0430\u043a*
#Невидимый Кулак