type=item
matchItems=cooked_beef cooked_chicken cooked_porkchop
texture=burger
nbt.display.Lore.*=ipattern:*\u0410\u0431\u0440\u0430\u043a\u0430\u0441 \u0411\u0443\u0440\u0433\u0435\u0440*
#*Абракас Бургер*