type=item
matchItems=netherite_sword diamond_sword golden_sword iron_sword
model=sawsword
nbt.display.Name=ipattern:*\u0428\u0438\u043f\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u043c\u0435\u0447*
#Шипованный меч