type=item
matchItems=glass_bottle potion dragon_breath
texture=thin_glass
nbt.display.Lore.*=ipattern:*\u041f\u0443\u0441\u0442\u043e\u0439 \u041f\u0443\u0437\u044b\u0440\u0451\u043a*
#*Пустой Пузырёк*
