type=item
matchItems=stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=bloody_sorrow
nbt.display.Lore.*=ipattern:**\u041a\u0440\u043e\u0432\u0430\u0432\u0430\u044f \u0421\u043a\u043e\u0440\u0431\u044c**
#*Кровавая Скорбь*