type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=firesword
nbt.display.Name=ipattern:\u0440\u0430\u0437\u043b\u043e\u043c\u0430\u043d\u043d\u044b\u0439 \u043c\u0435\u0447
#разломанный меч