type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=old_tanto
nbt.display.Name=ipattern:*\u0422\u0430\u043d\u0442\u043e*
nbt.display.Lore.*=ipattern:*\u0421\u0442\u0430\u0440\u043e\u0435*
#*Танто*
#*Старое*