type=item
matchItems=shield
model=royal_shield
model.shield_blocking=royal_shield_block
nbt.display.Name=ipattern:*\u042d\u043b\u0438\u0442\u043d\u044b\u0439\u0020\u0429\u0438\u0442\u0020\u041a\u0421*
#*Элитный Щит КС*