type=item
matchItems=crossbow
texture.crossbow=black_crossbow_standby
texture.crossbow_pulling_0=black_crossbow_pulling_0
texture.crossbow_pulling_1=black_crossbow_pulling_1
texture.crossbow_pulling_2=black_crossbow_pulling_2
texture.crossbow_arrow=black_crossbow_arrow
nbt.display.Name=ipattern:*\u0427\u0435\u0440\u043d\u044b\u0439\u0020\u0410\u0440\u0431\u0430\u043b\u0435\u0442*
#Черный Арбалет