type=item
matchItems=shield
enchantmentIDs=efficiency
model=trusty_armament
nbt.display.Name=ipattern:*\u041d\u0430\u0440\u0443\u0447
nbt.display.Lore.*=ipattern:*\u0433\u0435\u043d\u0435\u0440\u0430\u043b\u0430*
#Наруч
#*Генерала*