type=item
matchItems=netherite_sword
model=1braid
nbt.display.Name=ipattern:*\u043a\u043e\u0441\u0430*
nbt.display.Lore.*=ipattern:*\u0422\u0440\u0430\u043d\u0441\u0444\u043e\u0440\u043c\u0435\u0440*
#коса
#ОПИСАНИЕ: Трансформер