type=item
matchItems=netherite_sword diamond_sword golden_sword iron_sword carrot_on_a_stick
model=kumiko_staff
nbt.display.Lore.*=ipattern:*\u041f\u043e\u0441\u043e\u0445 \u041a\u0443\u043c\u0438\u043a\u043e*
#*Посох Кумико*