type=item
matchItems=netherite_sword diamond_sword
model=nichirin_kokushibou
nbt.display.Name=ipattern:*\u041a\u043b\u0438\u043d\u043e\u043a \u041a\u043e\u043a\u0443\u0448\u0438\u0431\u043e*
#*Клинок Кокушибо*