type=item
matchItems=glass_pane
model=sergo_pad_mega
nbt.display.Name=ipattern:*\u041f\u043b\u0430\u043d\u0448\u0435\u0442 mega*
nbt.display.Lore.*=ipattern:*\u041c\u0430\u0440\u043a\u0430 Serg*
#*Планшет mega*
#*Марка Serg*