type=item
matchItems=stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=primordial_ore_sword
nbt.display.Lore.*=ipattern:**\u041f\u0435\u0440\u0432\u043e\u0440\u043e\u0434\u043d\u044b\u0439 \u0420\u0443\u0434\u043d\u044b\u0439 \u041c\u0435\u0447**
#*Первородный Рудный Меч*