type=item
matchItems=arrow tipped_arrow spectral_arrow phantom_membrane
texture=ammobox
nbt.display.Name=ipattern:*\u0430\u043c\u0443\u043d\u0438\u0446\u0438\u044f*
nbt.display.Lore.*=ipattern:*\u0437\u0435\u043b\u0451\u043d\u0430\u044f*
#амуниция
#зелёная