type=armor
matchItems=chainmail_chestplate golden_chestplate iron_chestplate diamond_chestplate netherite_chestplate leather_chestplate

texture.chainmail_layer_1=black_rub_1
texture.gold_layer_1=black_rub_1
texture.iron_layer_1=black_rub_1
texture.diamond_layer_1=black_rub_1
texture.netherite_layer_1=black_rub_1
texture.leather_layer_1=black_rub_1

nbt.display.Lore.*=ipattern:*\u0427\u0451\u0440\u043d\u0430\u044f \u0440\u0443\u0431\u0430\u0448\u043a\u0430 \"DinBi\"*