type=item
matchItems=crossbow
model=m41a
model.crossbow_pulling_0=m41a_0
model.crossbow_pulling_1=m41a_1
model.crossbow_pulling_2=m41a_2
model.crossbow_pulling_1=m41a_3
nbt.display.Name=ipattern:*M41A*
#M41A