type=item
matchItems=wooden_sword iron_sword stone_sword golden_sword diamond_sword netherite_sword
model=kirito_sword
nbt.display.Lore.*=ipattern:*\u0412\u0440\u0430\u0437\u0443\u043c\u0438\u0442\u0435\u043b\u044c*
#*Вразумитель*