type=item
matchItems=crossbow
model=drum_rifle
model.crossbow_pulling_0=drum_rifle_0
model.crossbow_pulling_1=drum_rifle_1
model.crossbow_pulling_2=drum_rifle_2
model.crossbow_arrow=drum_rifle_arrow
nbt.display.Name=ipattern:*\u0411\u0430\u0440\u0430\u0431\u0430\u043d\u043d\u044b\u0439 \u0432\u0438\u043d\u0447\u0435\u0441\u0442\u0435\u0440*
#барабанный винчестер