type=item
matchItems=netherite_sword diamond_sword golden_sword stone_sword diamond_axe netherite_axe golden_axe iron_axe iron_sword
model=two_handed_sword
nbt.display.Name=ipattern:*\u0414\u0432\u0443\u0440\u0443\u0447\u043d\u044b\u0439 \u043c\u0435\u0447*
#Двуручный меч