type=item
matchItems=netherite_sword diamond_sword golden_sword iron_sword carrot_on_a_stick
model=zenitsu_blade
nbt.display.Name=ipattern:*\u041a\u0430\u0442\u0430\u043d\u0430*
nbt.display.Lore.*=ipattern:*\u041a\u043b\u0438\u043d\u043e\u043a \u0417\u0435\u043d\u0438\u0442\u0441\u0443*
#*Катана*
#*Клинок Зенитсу*