type=item
matchItems=iron_ingot gold_ingot netherite_ingot copper_ingot
texture=sun_ingot

nbt.display.Lore.*=ipattern:\u0421\u043e\u043b\u043d\u0435\u0447\u043d\u044b\u0439 \u041c\u0435\u0442\u0430\u043b\u043b
#Солнечный Металл