type=item
matchItems=crossbow
model=phandom
model.crossbow_pulling_0=phandom_0
model.crossbow_pulling_1=phandom_1
model.crossbow_pulling_2=phandom_2
model.crossbow_arrow=phandom_arrow
nbt.display.Name=ipattern:*\u0424\u0430\u043d\u0434\u043e\u043c*
#Фандом