type=armor
matchItems=chainmail_leggings golden_leggings iron_leggings diamond_leggings netherite_leggings leather_leggings

texture.chainmail_layer_2=raspberry_jack_pants_2
texture.gold_layer_2=raspberry_jack_pants_2
texture.iron_layer_2=raspberry_jack_pants_2
texture.diamond_layer_2=raspberry_jack_pants_2
texture.netherite_layer_2=raspberry_jack_pants_2
texture.leather_layer_2=raspberry_jack_pants_2

nbt.display.Lore.*=ipattern:*\u041c\u0430\u043b\u0438\u043d\u043e\u0432\u044b\u0435 \u0431\u0440\u044e\u043a\u0438 \"DinBi\" [\u0417\u0430\u043a\u0430\u0437 \u0434\u043b\u044f AvAkAdA]*