type=item
matchItems=iron_chestplate chainmail_chestplate diamond_chestplate golden_chestplate netherite_chestplate
texture=bez_much
nbt.display.Name=ipattern:*\u0411\u0435\u0437 \u043c\u0443\u0436\u0438\u043a\u043e\u0432*
