type=item
matchItems=iron_ingot gold_ingot netherite_ingot copper_ingot
texture=ifrite_ingot

nbt.display.Lore.*=ipattern:*\u0418\u0444\u0440\u0438\u0442\u043e\u0432\u044b\u0439 \u0421\u043b\u0438\u0442\u043e\u043a*
#*Ифритовый Слиток*